version: "3.7"
services:
  prometheus:
    container_name: dev-prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - ./prometheus_local_cfg.yaml:/etc/prometheus/cfg.yaml
    command:
      - "--storage.tsdb.retention.time=30d"
      - "--config.file=/etc/prometheus/cfg.yaml"
    networks:
      - bot-network

  postgres:
    container_name: dev-postgres
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=$PSQL_PASSWORD
    volumes:
      - /opt/solte-lab/postgres/data/pgdata:/var/lib/postgresql/data
#      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"
    networks:
      - bot-network

  zookeeper:
    image: bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: "kafka"
    image: bitnami/kafka:3
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

networks:
  bot-network:
    driver: bridge
