version: "3.7"
services:
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - ./prometheus_cfg.yaml:/etc/prometheus/cfg.yaml
    command:
      - "--storage.tsdb.retention.time=30d"
      - "--config.file=/etc/prometheus/cfg.yaml"
    networks:
      - bot-network

  postgres:
    container_name: op-postgres-db
    image: postgres:15.2
    environment:
      - POSTGRES_PASSWORD=$PSQL_PASSWORD
    volumes:
      - /opt/solte-lab/postgres/data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network

  bot:
    build:
      context: ../
      args:
        - VERSION=$VERSION
      dockerfile: Dockerfile
      target: op-bot
    container_name: bot_api
    env_file:
      - ./dev.env
    image: "bot:${VERSION}"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "2112:2112"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
