bot:
  build:
    context: ../
    args:
      - VERSION=$VERSION
    dockerfile: Dockerfile
    target: op-bot
  container_name: bot_api
  env_file:
    - ./dev.env
  image: "bot:${VERSION}"
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
  ports:
    - "2112:2112"
  networks:
    - bot-network
