CREATE DATABASE telegram_dev;

CREATE USER oranssi_worker PASSWORD 'dev_only_pwd';
CREATE DATABASE telegram_dev owner oranssi_worker ENCODING = 'UTF-8';

CREATE SCHEMA IF NOT EXISTS "oranssi_dialect";

CREATE TABLE IF NOT EXISTS "oranssi_dialect.users" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    chat_id INTEGER DEFAULT 0,
    user_name VARCHAR NOT NULL CONSTRAINT "Users_pk" UNIQUE,
    user_language VARCHAR NOT NULL DEFAULT 'en',
    words_topic VARCHAR NOT NULL DEFAULT 'all',
    words_seq_offset INTEGER NOT NULL DEFAULT 0,
    interaction BOOLEAN DEFAULT false,
    interaction_intensity INTEGER DEFAULT 0,
    interaction_next_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "oranssi_dialect.topics" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    topic VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS "oranssi_dialect.known_words" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    suomi VARCHAR NOT NULL,
    CONSTRAINT user_id_fk
        FOREIGN KEY (user_id)
            REFERENCES "oranssi_dialect.users"(id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "oranssi_dialect.words" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
	letter VARCHAR NOT NULL,
	topic_id BIGINT NOT NULL DEFAULT 0,
	suomi VARCHAR NOT NULL CONSTRAINT "words_PK" UNIQUE,
	english VARCHAR NOT NULL,
	russian VARCHAR NOT NULL,
    CONSTRAINT topic_id_fk
        FOREIGN KEY (topic_id)
        REFERENCES "oranssi_dialect.topics"(id)
        ON DELETE set default
);

CREATE TABLE IF NOT EXISTS "oranssi_dialect.phrases" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    topic_id BIGINT NOT NULL DEFAULT 0,
    suomi VARCHAR NOT NULL CONSTRAINT "words_PK" UNIQUE,
    english VARCHAR NOT NULL,
    russian VARCHAR NOT NULL,
    CONSTRAINT topic_id_fk
        FOREIGN KEY (topic_id)
            REFERENCES "oranssi_dialect.topics"(id)
            ON DELETE set default
);

-- TODO Think about small live example architecture
CREATE TABLE IF NOT EXISTS "oranssi_dialect.situations" ();