apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
      containers:
        - name: postgres
          image: postgres:15.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: pgsql-password
            # - name: POSTGRES_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: database-creds
            #       key: pgsql-username
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          # resources:
          #   requests:
          #     memory: "512Mi"
          #     cpu: "1500m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "2000m"
