[api.worker]
    port = 2112
    static_content_path = "static"
[api.ui]
    port = 8080
    static_content_path = "../../ui/"

[kafka_producer]
    connection_name = "kafka_producer"
    brokers = "192.168.100.4:9092"
    topic = "new_events"
    timeout = "15s"
    partitions = 1
    push_timeout = "1s"

[kafka_consumer]
    brokers = "192.168.100.4:9092"
    topic = "new_events"
    session_timeout = 6000
    batch_size = 100
    poll_timeout = "10s"
    group = "worker"
    connection_retries = 120
    auto_offset_reset = "latest"

[telegram]
    host = "api.telegram.org"
    token = ""

[scheduler]
    interval = "5s"

[postgresql.opdb]
    alias = "opdb"
    host ="localhost"
    port = 5432
    username = ""
    password = ""
    dbname = ""

[logging]
    loglevel = "debug"