[api.worker]
    port = 2112
    static_content_path = "static"

[api.ui]
    port = 8080
    static_content_path = "./ui/"

[telegram]
    host = "api.telegram.org"
    token = ""

[postgresql]
    host =""
    port = 5432
    username = ""
    password = ""
    dbname = ""

[logging]
    loglevel = "debug"